[profile.default]
src = "src"
out = "out"
libs = ["lib"]

optimizer = true

[rpc_endpoints]
bsc = "${BSC_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"

[etherscan]
bsc = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${ETHERSCAN_API_KEY}" }
