[profile.default]
src = "src"
out = "out"
libs = ["lib"]

optimizer = true

[rpc_endpoints]
bnb = "${BNB_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"

[etherscan]
bnb = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${ETHERSCAN_API_KEY}" }
